### PR TITLE
added cool_as_heck_algorithm 4 u

### PR DESCRIPTION
**Pull request by Thomas007G**
@Strum355 might be haXXor enough for this

### CODE REVIEW

**Review by Strum355 — APPROVED** [review]
bro is this bubble sort???? :heavy_check_mark:

**Comment by Strum355** [comment]
@OisinA pls review and merge :blush:

**Comment by Thomas007G** [comment]
> @OisinA pls review and merge 😊

yeah bro plz merge and review and then merge again plz xoxo

**Review by OisinA — APPROVED** [review]

**Review by ArthanJans — CHANGES_REQUESTED** [review]
Sorry no while loops allowed

**Review by ArthanJans — APPROVED** [review]
UwU

**Pull request merged**
